### ISSUE TITLE
该插件是否支持postgre？看了您的部分源码发现IdentityDialect里并不支持postgre

### ISSUE THREAD

**Issue by HaydenCyrus** [abel533/Mapper#220]
我的需求是，postgre下，新增成功返回自增主键的id

**Comment by abel533** [comment]
postgresql自增主键为id的时候可以返回。

**Comment by ruruiye** [comment]
这个Postgresql真的可以回写id么? 如下配置是失败的
Postgres 版本12.0, 通用mapper版本4.0

```
    @Id
    @KeySql(sql="SELECT currval('toolchain.country_id_seq'::regclass) AS id", order = ORDER.AFTER)
    @Column(insertable = false, updatable = false)
    private int id;
```
```
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.special.InsertListMapper
  not-empty: true
  style: camelhumpAndLowercase
  schema: toolchain
  before: false
```
```
       Country country = new Country();
        country.setCountryName("China");
        country.setCountryCode("CN");
        int id = countryMapper.insertSelective(country);
        return "Greetings from Spring Boot!" + country.getId() + id; // 此处打印出0 和 1
```
