### ISSUE TITLE
Postgresql KeySql 插入自增主键为空

### ISSUE THREAD

**Issue by Hongzhe** [abel533/Mapper#348]
keysql里的 sql 确实执行了，因为 sequence表里last_value的值自增了1，但是插入的时候 还是提示 主键为空
```
 @Id
 @KeySql(sql="select nextval('test_table_id_seq'::regclass)",  order = ORDER.BEFORE)
 private Integer id;
```

用的mapper的版本是2.0.3, pg的版本是9.5
配置文件如下

```
 mybatis: 
   typeAliasesPackage: xxxx.bean
   mapperLocations: classpath: xxxxx/mapper/*.xml
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.special.InsertListMapper
  order: BEFORE
pagehelper: 
  helper-dialect: postgresql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
```
------------- 分割线 --------------
更新，看了之前的已经被关闭的issue，改成下面这样就行了
```
@Id
@KeySql(sql="SELECT currval('test_table_id_seq'::regclass)", order = ORDER.AFTER)
@Column(insertable = false)
private Integer id;
```
