### ISSUE TITLE
Postgresql 使用KeySql回写ID失败

### ISSUE THREAD

**Issue by ruruiye** [abel533/Mapper#752]
Postgres 版本12.0, 通用mapper版本4.0, 基于Springboot 2.1和
```
org.mybatis.spring.boot:mybatis-spring-boot-starter:2.1.2
```

```
@Id
    @KeySql(sql="SELECT currval('toolchain.country_id_seq'::regclass) AS id", order = ORDER.AFTER)
    @Column(insertable = false, updatable = false)
    private int id;
```
```
mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.special.InsertListMapper
  not-empty: true
  style: camelhumpAndLowercase
  schema: toolchain
  before: false
```
```
Country country = new Country();
        country.setCountryName("China");
        country.setCountryCode("CN");
        int id = countryMapper.insertSelective(country);
        return "Greetings from Spring Boot!" + country.getId() + id; // 此处打印出0 和 1
```
